[env:freenove-esp32-s3-n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = freenove-esp32-s3-n8r8
framework = arduino
extra_scripts = pre:scripts/version.py

monitor_speed = 115200
upload_speed = 460800
; PlatformIO erkennt den angeschlossenen USB-Port automatisch.
; Optional beim Aufruf überschreiben: pio run --target upload --upload-port COM3

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DBOARD_HAS_PSRAM
